import type { ReportRecord } from './types';

/**
 * Fixtures para o módulo Relatórios. Substituiremos por uma query
 * ao MSW (e depois à API) assim que o backend estiver disponível.
 */
export const REPORT_FIXTURES: readonly ReportRecord[] = [
  {
    id: 'rpt-001',
    date: '2026-07-12T08:30:00Z',
    patient: 'Maria Silva Santos',
    company: 'Falcão Construções',
    sector: 'Engenharia',
    exam: 'ASO Admissional',
    status: 'apto',
    professional: 'Dra. Beatriz Lima',
    notes: 'Exame clínico + audiometria sem alterações.',
  },
  {
    id: 'rpt-002',
    date: '2026-07-13T09:00:00Z',
    patient: 'João Pedro Almeida',
    company: 'Falcão Construções',
    sector: 'Obras',
    exam: 'ASO Periódico',
    status: 'apto_restricao',
    professional: 'Dr. Rafael Tavares',
    notes: 'Restrição para trabalho em altura até reavaliação.',
  },
  {
    id: 'rpt-003',
    date: '2026-07-14T10:30:00Z',
    patient: 'Ana Carolina Souza',
    company: 'Falcão Engenharia',
    sector: 'Administrativo',
    exam: 'ASO Periódico',
    status: 'agendado',
    professional: '—',
  },
  {
    id: 'rpt-004',
    date: '2026-07-15T07:45:00Z',
    patient: 'Carlos Eduardo Pereira',
    company: 'Falcão Construções',
    sector: 'Manutenção',
    exam: 'ASO Demissional',
    status: 'realizado',
    professional: 'Dra. Beatriz Lima',
  },
  {
    id: 'rpt-005',
    date: '2026-07-11T14:00:00Z',
    patient: 'Patrícia Mendes',
    company: 'Falcão Construções',
    sector: 'Segurança do Trabalho',
    exam: 'ASO Periódico',
    status: 'faltou',
    professional: '—',
    notes: 'Remarcado para 20/07.',
  },
  {
    id: 'rpt-006',
    date: '2026-07-10T11:00:00Z',
    patient: 'Lucas Ferreira',
    company: 'Falcão Construções',
    sector: 'Obras',
    exam: 'ASO Mudança de Função',
    status: 'inapto',
    professional: 'Dr. Rafael Tavares',
    notes: 'Encaminhado ao ortopedista.',
  },
  {
    id: 'rpt-007',
    date: '2026-07-09T08:00:00Z',
    patient: 'Renata Oliveira',
    company: 'Falcão Engenharia',
    sector: 'Engenharia',
    exam: 'ASO Admissional',
    status: 'apto',
    professional: 'Dra. Beatriz Lima',
  },
  {
    id: 'rpt-008',
    date: '2026-07-15T15:00:00Z',
    patient: 'Felipe Marques',
    company: 'Falcão Construções',
    sector: 'Logística',
    exam: 'ASO Periódico',
    status: 'agendado',
    professional: '—',
  },
] as const;
